### ISSUE TITLE
Android not working

### ISSUE THREAD

**Issue by Roberto7766** [Unity-Technologies/barracuda-release#131]
I made a small project to test Barracuda. I used version 1.2.1 otherwise I had an error. The NN is fed by a constant value 0.1f and the time for executing the network is shown on the display.
The project works correctly if run on PC: the NN output is correct if compared with onnxruntime in python.
The issue is when compiled for Android: the NN output is wrong (zero for all the values) and it takes too long to obtain the result (about one second; for this rather small net I expect something faster).
Here the project ("Execute" is invoked pressing a button):

using System.Collections;
using System.Collections.Generic;
using Unity.Barracuda;
using UnityEngine;
using UnityEngine.UI;

public class NeuralNetwork : MonoBehaviour
{

    public NNModel model;
    private IWorker worker;

    private bool exec;
    private float duration = 0;

    public Text ExecTime;
    public Text Out1;
    public Text Out2;
    public Text Out3;
    public Text Out4;
    public Text Out5;

    // Start is called before the first frame update
    void Start()
    {
        exec = false;
    }

    // Update is called once per frame
    void Update()
    {
        if (exec)
        {
            exec = false;
            Debug.Log("Execute");
            float startTime = Time.realtimeSinceStartup;

            var Bmodel = ModelLoader.Load(model);
            worker = WorkerFactory.CreateWorker(WorkerFactory.Type.Auto, Bmodel);

            float[] floatValues = new float[256 * 128 * 3];

            for (int i = 0; i < floatValues.Length; ++i)
            {
                floatValues[i] = 0.1f;
            }

            Tensor input = new Tensor(1, 256, 128, 3, floatValues);

            worker.Execute(input);
            var output = worker.CopyOutput();
            float[] NNout = output.ToReadOnlyArray();

            duration = Time.realtimeSinceStartup - startTime;
            ExecTime.text = "Sec: " + duration.ToString();
            Out1.text = NNout[0].ToString();
            Out2.text = NNout[1].ToString();
            Out3.text = NNout[2].ToString();
            Out4.text = NNout[3].ToString();
            Out5.text = NNout[4].ToString();

            input?.Dispose();
            worker?.Dispose();

        }
    }

    public void Execute()
    {
        exec = true;
    }
}

At this link is the NN model:
https://drive.google.com/file/d/1y9wvwVXYkOYyIHfykMrYNjtw1PFh-_iz/view?usp=sharing

Thanks

**Comment by AlexRibard** [comment]
@Roberto7766 thank you for sharing the model.
Are you trying on CPU or GPU? Vulkan or OpenGL?
Let me know

**Comment by Roberto7766** [comment]
@AlexRibard I tried Vulkan and GPU. I made now an attempt with CPU and it works. Few details: the first run is 3 times slower than the successive runs. GPU does not work (it returns always zero and it is even slower than CPU).
I suppose that GPU is faster than CPU: is it possible to make the GPU work?
I also notice that during NN computation the APP is "freezed" waiting for the computation to finish. Is there a way to implement a sort of multithreading in order not to stop the APP while the NN is computed?
Thanks

**Comment by AlexRibard** [comment]
A few things,
* If using the `ComputePrecompiled` backed (or default GPUWorker) the first run is slow on purpose because we do a number of optimizations/baking out/kernel selecting that we would otherwise do during the executions.
You can validate that the successive runs (after the first one) are faster than a generic `Compute` worker.

* Ok, if you are red on Vulkan we'll check to see why it's not working on your device. @Aurimasp do you have a similar device as @Roberto7766 ?

* Actually there is a solution. The main problem is that the execution takes more than a frame time (> 33ms) (which is still strange given your network that said, we'll investigate a bit on that front too).
https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation~/ModelExecution.md
> Scheduled execution
We allow you to split the execution over a number of frames by only executing a number of layers per frame

**Comment by Roberto7766** [comment]
@AlexRibard do you have any update on this issue? Thanks.

**Comment by Aurimasp** [comment]
We couldn't reproduce the issue (outputs = 0) so far on Google Pixel 4 and Samsung Galaxy Note 8 with Vulkan graphics api. Which Android device you are using? (Adding screenshots Android vs Desktop)

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/26163719/106769199-5df44c00-6645-11eb-95b2-5a967e49a930.png">

**Comment by Aurimasp** [comment]
I've also checked it on OpenGLES and I got all 0. Changing to Vulkan should solve the issue.

**Comment by Roberto7766** [comment]
I tried on a Xiaomi Redmi note 5 (android 9) with Vulkan and it still does not work.

**Comment by Aurimasp** [comment]
One more thing to try. Try to remove OpenGLES from the Graphics API list to make sure the device won't fall back to it. If current drivers do not support Vulkan, the app may use the second option.

<img width="574" alt="image" src="https://user-images.githubusercontent.com/26163719/106933194-50ac8f80-6721-11eb-9580-b65a5a479e4e.png">

<img width="584" alt="image" src="https://user-images.githubusercontent.com/26163719/106933103-383c7500-6721-11eb-954e-c123424ab1c6.png">

**Comment by Roberto7766** [comment]
Is already removed from the list, only Vulkan is present.

**Comment by Aurimasp** [comment]
I was able to reproduce the issue and logged it into our database.
Issue Tracker link should appear soon: https://issuetracker.unity3d.com/product/unity/issues/guid/BAR-23 
Thanks for reporting the issue.

**Comment by FlorentGuinier** [comment]
Closing as bug is now tracked using the issuetracker link above.
