### ISSUE TITLE
Error during MatMul using ComputeOps and PrecompiledComputeOps

### ISSUE THREAD

**Issue by Eric-Lee** [Unity-Technologies/barracuda-release#148]
When attempting to call MatMul using ComputeOps or PrecompiledComputeOps, I get the following error:

```
Thread group size must be above zero
UnityEngine.ComputeShader:Dispatch(Int32, Int32, Int32, Int32)
Unity.Barracuda.ComputeFunc:Dispatch(Int32, Int32, Int32) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/Core/Backends/BarracudaReferenceCompute.cs:2627)
Unity.Barracuda.ComputeFunc:Dispatch(ValueTuple`3) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/Core/Backends/BarracudaReferenceCompute.cs:2610)
Unity.Barracuda.ComputeKernel:Dispatch() (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/Core/Backends/BarracudaCompute.cs:729)
Unity.Barracuda.ComputeOps:Dense(Tensor, Tensor, Tensor, FusedActivation) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/Core/Backends/BarracudaCompute.cs:934)
Unity.Barracuda.ComputeOps:MatMul(Tensor, Boolean, Tensor, Boolean) (at Library/PackageCache/com.unity.barracuda@1.3.0-preview/Barracuda/Runtime/Core/Backends/BarracudaCompute.cs:899)
```
There is no error if I use ReferenceComputeOps.

Tensor X has shape (115095, 1, 1, 40) [NHWC] and Tensor Y has shape (40, 1, 1, 1) [NHWC]. No transposing.

Doing my best to trace the error, I see that Unity is attempting to Dispatch kernel "Dense_Tilled2x2_Cached" with thread dimensions (0, 14387, 1). It looks like since every candidate entry returned by ComputeKernelLibrary.Dense() is invalid for these tensor shapes, ComputeKernel.BestKernel returns the kernel associated with the first entry in the entries list even though it is also invalid. Maybe it should use the reference compute kernel as a backup in this case.

I tried achieving the same result using a Mul -> ReduceSum but it is an order of magnitude slower.

Thanks for any help!

**Comment by Eric-Lee** [comment]
I will try reshaping Tensor X to (38365, 3, 1, 40) to get the kernel dispatch arguments < 65535.

**Comment by AlexRibard** [comment]
@Eric-Lee I have fixed the issue in master, expect to see the fixes in 1.3.1 (should be release by next week).
The bug was linked to non multiple of 2 for H and W.
Can you try to make X shape of (115096, 1,1, 40) in the meantime?

**Comment by Eric-Lee** [comment]
Thanks for the quick response, Alex. I tried Mul with X shape (115096,1,1, 40) but I'm still receiving the same error. 

I'm not sure if this is relevant or on the right track, but it looks like the output tensor width being 1 is also causing problems. For example in this snippet from ComputeKernelLibrary.Dense:
```
entries.Add(new Entry("Dense_Tilled2x2_Cached",
      Int3(w/2, h/2),                                 BigO(X.flatWidth)/2,
      StrictAnd(w % 2 == 0 && h % 2 == 0 && X.flatWidth % 32 == 0),
  (Application.platform == RuntimePlatform.Android) ||
  (Application.platform == RuntimePlatform.IPhonePlayer) ||
  (ComputeInfo.graphicsDeviceVendor.Contains("Intel"))
));
```
w=1 causes a 0 dispatch dimension and also an invalid entry.

**Comment by Eric-Lee** [comment]
Thank you, after updating to 1.3.1 my issues are fixed!

**Comment by AlexRibard** [comment]
great!
